### ISSUE TITLE
Cannot seem to launch

### ISSUE THREAD

**Issue by DevMichael97** [ProjectSWGCore/NGECore2#1290]
Delete comment

**Comment by madsboddum** [comment]
It isn't obvious, but this code base was abandoned some time ago. The new one can be found [here](https://bitbucket.org/projectswg/holocore).

**Comment by juliax123** [comment]
Thanks buddy, appreciate it. @Ziggeh

**Comment by juliax123** [comment]
@Ziggeh, bud can you help me out with setting holocron up, i'm not having a lot of success. exchange emails and talk about it or something or an instruction list more detailed than one that is on the site.

**Comment by GeneUNCG** [comment]
@juliax123 Still need help?

**Comment by juliax123** [comment]
Hi!  No friend I'm fine

Michael A. Harrison
The University of Memphis 
ResNet Technician for Residence Life
135 Centennial Place, Memphis, TN 38152
(901) 678-4042 ResNet Desk
